### ISSUE TITLE
Feed information from acoustid

### ISSUE THREAD

**Issue by maletor** [Shurelia/wcd2pth-sort#1]
> Your torrent files from WCD, with their original names (in the format of Artist - Album - Year (Media - Format - Lossless).*?.torrent). So unfortunately, only torrents snatched post-2012 will be checked.

This is an impossible requirement for me to meet. However, we should be able to generate this data from AcoustID database though then feed it in here and call `pth.browse` right?

**Comment by maletor** [comment]
Actually, this might be simpler and better:

```bash

for dir in *; do
  for file in "$dir"/*.flac; do
    filename=$(metaflac --show-tag=ARTIST --show-tag=ALBUM --show-tag=DATE "$file" | xargs -d'\n' | sed 's/artist=//i' | sed 's/album=/- /i' | sed 's/date=/- /i' | sed 's/$/\ \(CD\ -\ FLAC\ -\ Lossless\)/' | tr -d '\n')
    break 1
  done
  
  /home/maletor/mktorrent/mktorrent -l 21 -p -s PTH -a "https://please.passtheheadphones.me/f60939572f79ec1964537c84607ec36f/announce" "$dir" -o /home/maletor/torrents/"$filename".torrent; 
done
```

**Comment by Shurelia** [comment]
@maletor Great idea! Do be careful with it, though, as it's going to list everything as a CD release, when it could potentially be a web or vinyl.
